### ISSUE TITLE
`install` needs attention

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1196]
Summary issue for `install`s issues to make the state of things more obvious:

- [x] #1404 
- [x] #1184 permission issues
- [x] #1173 doesn't use common code base
- [x] #1147 UX
- [ ] #1146 missing feature
- [x] #1127 connection reuse issue
- [x] #1110 UX
- [x] #1049 missing feature/API limitation
- [x] #1006 insufficient documentation
- [x] #1002 unclear what it is/if it is something (still)
- [x] #956 inappropriate exit code
- [x] #937 missing feature
- [x] #875 possibly done already (@yarikoptic: probably not - in case of recursive invocation when original wasn't recursive)
- [ ] #450 missing feature

**Comment by bpoldrack** [comment]
Not sure, why #1011 is listed here. What would it mean to check this box?

**Comment by mih** [comment]
Indeed, removed. Checking the box usually means "done" or "dealt with".

**Comment by mih** [comment]
This is largely dealt with, or now worked on in #3966
