### ISSUE TITLE
`publish` needs attention

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1197]
- [ ] fix variant of #1533 and let `AnnexRepo.copy_to()` return full JSON without any intermediate error detection
- [ ] #1494 publishing from within subdataset should update parents web metadata
- [ ] #1390 failed to publish new sub-dataset 
- [ ] #1344 publish --missing=inherit won't work in general
- [ ] #1275 publish should publish current branch
- [ ] #1194  missing feature: needs progress bar for publish
- [ ] #921 missing feature: mark non-redistributable materials
- [x] #628 missing feature: Report errors which happen during git push
- [ ] #16 publish for backup

**Comment by mih** [comment]
@bpoldrack @yarikoptic This is WIP now. Given that general dissatisfaction with what `publish` does right now. I will skip the step of doing a plain RF first and only later change behavior. Instead I will RF and adjust the tests accordingly. Then we should meet and see if this resulting behavior is something we can all agree on. Meanwhile, I will use the issues above as guidelines re what we expect. Feel free to add more.

**Comment by yarikoptic** [comment]
who said that I was dissatisfied with current behavior?  it actually does what I usually need!  there are problems of cause but general behavior is acceptable.  my typical invocation is

```
datalad publish --to=datalad-public -r --missing=inherit
```
where I tell it to "publish all the changes" and try to create subdatasets on remote sibling if not yet present while inheriting settings from their parents. It also used to consider --since by default so was fast/usable! ;-)

**Comment by mih** [comment]
@yarikoptic yes, but see #1344 for one example.

**Comment by yarikoptic** [comment]
thanks, left a comment there ;)

**Comment by mih** [comment]
Obsolete issue, replaced by https://github.com/datalad/datalad/projects/9
