### ISSUE TITLE
`create-sibling*` needs attention

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1198]
Summary issue for `publish`s issues to make the state of things more obvious:

- [x] #1192 UX/optimization
- [x] #1188 missing feature/robustness
- [x] #1040 large scale refactoring need?
- [x] #1015 inappropriate exit code
- [x] #972 UX
- [ ] #925 missing feature
- [x] `--since` for all recently added subdatasets

**Comment by mih** [comment]
The majority was addressed. The remaining #925 doesn't need a meta issue like this.
