### ISSUE TITLE
`update` needs attention

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1199]
Update needs an RF to bring it in line with the more recently refurbished commands. Please share you ideas on what needs to be done. Further work needs decisions on the following @bpoldrack @yarikoptic:

- [ ] update --merge fails without giving a clear message (conflicts in .gitmodules) why #1525
- [x] Implement `--reobtain-data`, possibly based on #1203
- [x] Decide whether `--merge` should become ON by default
- [x] Give some (any) indication of available updates when run without `--merge` -- at present it will simply say nothing, and even say nothing (and do nothing) if there are actual updates (#1219)
- [ ] Process trees of datasets and save potentially updated states accordingly (see comment at the end of #1370)
- [x] Unify with other commands and say "what to update" rather than "from where" as the primary argument(s) #1185 
- [x] Simplify complexity by just supporting an update from one sibling at a time, instead of am ordered list. It could be done for a list, but complexity explodes when considering trees of datasets at once.
- [ ] if a path to a file or directory *within* a dataset is given as input: shall we fail and ask for root paths only, or shall we inform that the associated dataset will be updated? MIH: leaning towards the latter.
- [ ] decide whether `--fetch-all` combined with `--merge` should remain "get and apply all available update", or whether `--fetch-all`should literally mean just that and `--merge` would only merge what is indicated by `--sibling` (MIH: the latter is cleaner)
- [x] for updating an annex repo switch away from `annex merge` to `annex sync --no-push --no-pull` in order to properly handle managed branches (e.g. in v6 repos)
- [x] decide on return value(s). MIH: Seems JSON-like output makes most sense. Proposal:
    * which dataset was updated
    * from which sibling (report actual name in case of requested default)
    * state/commit/tag? updated from and to, in case of merge-enabled update
- [x] Resolution for #1007 
- [x] Resolution for #953
- [x] User reporting #868 
- [x] Multi-branch support #793
- [x] No tags fetched #712 
- [x] #705
- [x] #1306 
- [x] #1307 
- [ ] #1313 more strategies for `-reobtain-data`

**Comment by mih** [comment]
OK, guys. Silence is approval. Consider questions and conditional statements above as imperative. Now in execution phase.

**Comment by mih** [comment]
See #1304

**Comment by yarikoptic** [comment]
well -- I trust you @mih ;) and had no chance yet to give a proper consideration to the list which managed to sneak in unnoticed (I guess when I was again shoveling the damn snow) ;)

**Comment by mih** [comment]
`update` has seen a few improvements over time. This assessment is now rather outdated and can be closed.
