### ISSUE TITLE
Content tagging, selective content processing, and preferred content

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1280]
This topic comes up over an over. This issue provides an overview:

- [ ] #1582 design question
- [x] #1442 be aware!
- [ ] #1347 install command should expose "*wanted*" options, get should use those as well 
- [ ] #925 create-sibling --wanted=manual
- [ ] #921 RFC: mark non-redistributable materials
- [ ] #874 TODO: tag every file we obtain using some kind of credentials as "restricted" and inherit it while extracting archives
- [ ] #588 (a bit far fetched wrt this topic)
- [ ] #25 "lean" views
- [ ] #16
- [ ] #6

**Comment by mih** [comment]
Closing FOI after a long time.
