### ISSUE TITLE
`siblings` needs attention

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1520]
Here is the remaining TODO after #1500:

- [x] rewrite description #1484 
- [x] sibling/dataset configuration via templates #1462 
- [ ] wanted policy setup #925 (related #921)
- [ ] registration via datalad RIs #1438 
- [ ] annex-only sibling tracking/update #1363
- [x] figure out if we want to treat "here" as yet another sibling and have the very same command also manipulate a standalone dataset (e.g. for description, wanted, ....). If so, how to indicate this best? `--name` no name could be `here`, but the we would need something for "give me all info about all remotes".
- [x] check (maybe via coverage) which parts of the legacy `add_sibling` became obsolete and gut the code accordingly
- [x] insufficient documentation #1017 
- [x] scary low-level logs #1519

**Comment by mih** [comment]
I am closing this. We have the `cmd-siblings` label now, which can provide the same overview
