### ISSUE TITLE
Debian packages for dependencies

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2194]
#### What is the problem?
To get new shiny 0.10 release out we should make Debian/NeuroDebian ready for it.  This issue to collect info on 3rd party dependencies we should have

##### Recommends (so better to have)
Among those available I haven't analyzed which are present in what debian/ubuntus so some might need backports
- [x] python-lzma
- [x] python-dicom (neuroimaging-only #2358)
- [x] python-nibabel (neuroimaging-only #2358)
- [ ] python-grabbits (neuroimaging-only #2358)
- [ ] python-bids (neuroimaging-only #2358)
- [ ] datalad-neuroimaging (almost done)

FWIW, python-whoosh pkg is very lean -- doesn't require any additional packages 

##### Suggests
- [x] exifread -- python-exif package
- [x] exempi
- [x] python-xmp-toolkit -- `python-libxmp`
- [x] python-mutagen
- [x] python-duecredit (actually we added it to python setup.py but not yet use it anyhow?!)
- [x] python-libxmp
- [ ] if #2358 separation into datalad-neuroimaging happens -- needs to be packaged as well

**Comment by mih** [comment]
Pushed a base for a future Debian packaging of the neuroimaging extension https://github.com/datalad/datalad-neuroimaging/tree/debian

**Comment by mih** [comment]
Done (at least in the context of datalad-core)
