### ISSUE TITLE
Brain dump on GitPython removal

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2879]
I am aware that this idea is unpopular, but I am yet to be convinced that carrying around a repository instance in an otherwise entirely stateless setup is adding something valuable enough to be worth the cost. However, this is not to debate this point but rather to summarize what I know about the situation.

### Usage patterns

[ km: Updated for #2902 and #3530 ]

Direct usage of the GitPython API in non-Repo class code is most problematic. Here are those in Datalad-core that I am aware of (`repo` is the GitPython repository object):

- [ ] repo.remotes[remote].refs (create-sibling, publish)
- [ ] repo.repo.commit() (publish)
- [ ] repo.remotes[remote].refs[remote_branch_name] (publish)
- [ ] repo.close() (ls)
- [X] repo.git.show() (gone with #2902)
- [ ] repo.git.merge_base() (GitRepo)
- [X] repo.git.rev_parse() (all but two gone with #2902)
- [X] repo.git_dir (gone with #2902)
- [ ] repo.git (GitRepo, AnnexRepo)
- [X] repo.git.for_each_ref()
- [X] repo.git.log()
- [X] repo.git.ls_tree()
- [X] repo.git.cat_file

and additionally in the associated tests

- [X] repo.git.rev_list()
- [X] repo.head.commit.message
- [x] repo.commit().hexsha
- [X] repo.git.reset()
- [ ] repo.submodule() (GitRepo tests)

### Data structure/object use

Except for PushInfo and Blob these are pretty harmless, as they either do not need a Repo instance, or are more or less static objects.

- [x] git.GitConfigParser
- [x] git.remote.PushInfo
- [x] git.objects.blob.Blob
- [ ] git.exc.InvalidGitRepositoryError
- [ ] gitdb.exc.BadName
- [ ] git.exc.GitCommandError
- [ ] git.exc.NoSuchPathError

**Comment by bpoldrack** [comment]
Actually the only thing unpopular thing is making it happen, I guess. ;-)

Just to clarify: Those usage patterns are what you found outside of or including our `*Repo` classes?

**Comment by yarikoptic** [comment]
In my view removal is indeed just a call to reimplement what we already use from it. Could be done? Sure. Is it worth the effort to redo the wheel? Don't think so.
Absorbing all interaction with it within our Repo classes and not leaking it outside of them - that is worthwhile... is it a priority? I don't think so, but if someone does that part - I won't mind

**Comment by kyleam** [comment]
@yarikoptic
> is it a priority? I don't think so, but if someone does that part - I won't mind

This is my thinking as well, but I'll add:  If someone initiates that, I will help, especially with the cases where I've used repo.git heavily (e.g., run/rerun, check_dates).

**Comment by mih** [comment]
> Those usage patterns are what you found outside of or including our *Repo classes?

Correct.

**Comment by kyleam** [comment]
Eh, sorry, looking again at this, *many* of those `repo.git`s are mine :‑/ .  I wasn't aware of history like #1600.  Based on that, there seems to already have been agreement that gitpython should be avoided outside of `GitRepo`.

I'm not quite sure how I came to the incorrect conclusion that `repo.git` use was preferred if there wasn't a fitting `GitRepo`, but I'm still confused by bits like 

https://github.com/datalad/datalad/blob/b0cfdbb1b24a0a36fa48be6f7a2c68ed88d029a9/datalad/support/gitrepo.py#L1707-L1717

Presumably that is stale and should be removed?

Also, if we're going to discourage gitpython calls, I think it'd be useful to have a public method that wraps `_git_custom_command` (or that simply is it) for one-off commands.   This could even be several methods that wrap common `_git_custom_command` patterns/outputs: boolean, str, list.

**Comment by bpoldrack** [comment]
> or at least clarify that it's talking about use within GitRepo? 
Well, originally I thought that was clear by the leading underscore. But yes, this should be clarified and the original intention was to allow for a quick first implementation of a method and then using `self.cmd_call_wrapper` (`GitRunner`) directly later on. But we clearly failed to follow this paradigm (or to take the second step to be more accurate). However, I think that's still, what we should aim for in order to clean that chaos and better deal with errors etc.

> I think it'd be useful to have a public method that wraps _git_custom_command (or that simply is it) for one-off commands

Actually, the reason for its existence is the opposite: If you need a git call this allows to quickly make this a method of `GitRepo` that is to be used in higher-level code, so you could care for high-level while not spending much time on proper low-level error handling etc., but still have it where it belongs and where it can be ironed out/safeguarded/etc. later on in a different PR and possibly by someone else.

**Comment by kyleam** [comment]
Thanks, @bpoldrack

> Well, originally I thought that was clear by the leading underscore.

Sorry, my comment wasn't clear. With "use" above, I'm not talking about `_git_custom_command`, but about GitPython. Reading the "without the need to figure out, how this is done via GitPython" part, I'd think "OK, so idealing I should try to use GitPython when creating GitRepo methods". But it sounds like, while GitPython use outside GitRepo is the biggest concern, we also want to avoid GitPython **within** GitRepo methods, but to me this comment suggests it is the preferred way.

**Comment by bpoldrack** [comment]
Right, I missed that part of the comment. This should be removed from that comment. Your interpretation is correct, but the comment is outdated. ;-)
