### ISSUE TITLE
Retire `annotate_paths()`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3368]
RF the following remaining users:

- [x]  `add` -- to be retired via `rev_save`
- [x]  `create`
- [x]  `create_sibling` #5011
- [x]  `drop` #5012
- [x]  `get`
- [x]  `publish` -- moving to deprecated with https://github.com/datalad/datalad-deprecated/pull/28
- [x]  `remove` -- fixed with #6111
- [x]  `uninstall`
- [x]  `update`
- [x]  `clean`
- [x]  `diff` -- `rev_diff` replacement ready
- [x]  `save`
- [x] `unlock` (gh-3459)
- [x]  `aggregate` -- workaround implemented in #6128 to-be-retired via new metadata stack from -revolution
- [x] `metadata` -- workaround implemented in #6128 to-be-retired via new metadata stack from -revolution (@mih tried to RF it to use `status()` instead, but this is so intertwined with the assumptions and behavior of `annotate_paths()` that it would end up being a rewrite -- a rewrite that is already ongoing from a different angle by @christian-monch )
