### ISSUE TITLE
Strip normalize_paths()

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4595]
Essentially, this functionality is from a time where the Repo classes had to be considered part of the primary API. But now there are many discrepancies between the actual API (commands) and these function.

A key issue of this approach is that its semantics are incompatible with generator-style implementations. A list of file names passed to a method will cause the all results to be assembled into a list before the method can communicate any results back to a caller (see `match_return_type` which is default-on). This causes unresponsiveness issues of various kinds and has led to alternative implementations of methods using this approach, and yielded several abandonned duplicates (see below).

Moreover, for each an every file passed to any such method (not once, but per each file!) a repositories root dir is fully resolved on the file system (this can be a slow operation, and when saving 10k files, it is done 10k times). If absolute paths are given, or paths of the style `./somepath` or `../somepath` (which is not a rare case), also the parent path of each file path is fully resolved. Taken together, this decorator performs between 1 and 2 `resolve()` calls per given file. This problem is compounded by the fact that pretty much all calling command implementations have already performed such tests and conversions.

Ping @bpoldrack if you recall a full list of the relevant aspects, please add here.

Usage is limited to
- datalad/support/annexrepo.py
- datalad/support/gitrepo.py
- datalad/support/tests/test_gitrepo.py

Outside the tests `GitRepo` uses it for

- [ ] `add()`: to be gone #4872 
- [ ] `remove()`
- [ ] `get_last_commit_hexsha()`: used in 3 locations, if adjusted, the decorator could be dropped
- [x] `_git_custom_command()`: to be gone #4850 

Usage in `AnnexRepo`:

- [ ] `get()`
- [ ] `add()`: to be gone #4872 
- [ ] `get_file_key()`: replace by get_file_props() see https://github.com/datalad/datalad/pull/6104#issuecomment-948715491
- [ ] `unlock()`
- [ ] `unannex()`
- [ ] `find()`
- [ ] `file_has_content()`: replace by get_file_props() see https://github.com/datalad/datalad/pull/6104#issuecomment-948715491 -- last user `metadata.py`, the rest are old tests.
- [ ] `is_under_annex()`: replace by get_file_props() see https://github.com/datalad/datalad/pull/6104#issuecomment-948715491 -- last users `download_url`, `add_archive_content`, and `metadata.py`
- [ ] `drop()`
- [ ] `whereis()`
- [ ] `info()`
- [ ] `remove()`
- [ ] `is_available()`
- [x] `_annex_custom_command()`
- [ ] `migrate_backend()`
- [ ] `get_file_backend()`: replace by get_file_props() see https://github.com/datalad/datalad/pull/6104#issuecomment-948715491
- [ ] `copy_to()`

There seems to be no need to tackle this all at once.

However, I do not see a good migration path other than fully deprecating all methods that use this approach, and somehow provide similarly named replacements. The key issue here is that `match_return_type` is `True` for all but 3 implementations. Whether or not a deprecation warning should be communicated would depend on whether the underlying method would actually behave differently with or without a list of filenames passed.

**Comment by adswa** [comment]
There seem to be 21 instances of methods decorated with ``annotate_paths``, all almost exclusively in gitrepo and annexrepo:

```
❱ git grep @normalize_paths
datalad/support/annexrepo.py:1476:    @normalize_paths
datalad/support/annexrepo.py:1612:    @normalize_paths
datalad/support/annexrepo.py:1735:    @normalize_paths
datalad/support/annexrepo.py:1797:    @normalize_paths
datalad/support/annexrepo.py:1845:    @normalize_paths
datalad/support/annexrepo.py:1872:    @normalize_paths(map_filenames_back=True)
datalad/support/annexrepo.py:1938:    @normalize_paths
datalad/support/annexrepo.py:1957:    @normalize_paths
datalad/support/annexrepo.py:2260:    @normalize_paths
datalad/support/annexrepo.py:2365:    @normalize_paths
datalad/support/annexrepo.py:2481:    @normalize_paths(map_filenames_back=True)
datalad/support/annexrepo.py:2687:    @normalize_paths(match_return_type=False)
datalad/support/annexrepo.py:2737:    @normalize_paths(serialize=True)
datalad/support/annexrepo.py:2802:    @normalize_paths
datalad/support/annexrepo.py:2834:    @normalize_paths
datalad/support/annexrepo.py:2934:    @normalize_paths(match_return_type=False)  # get a list even in case of a s>
datalad/support/gitrepo.py:1180:    @normalize_paths
datalad/support/gitrepo.py:1285:    @normalize_paths(match_return_type=False)
datalad/support/gitrepo.py:1562:    @normalize_paths(match_return_type=False)
datalad/support/tests/test_gitrepo.py:440:        @normalize_paths
datalad/support/tests/test_gitrepo.py:444:        @normalize_paths
adina@muninn in ~/repos/datalad on git:mnt-6644
❱ git grep @normalize_paths | wc -l
21
```

from my experience with #6745 an straightforward replacement does not necessarily exist, but at least in that PR it was possible to use other functions. Might be possible in other places, too?

And I re-discovered a [comment](https://github.com/datalad/datalad/pull/6745#pullrequestreview-995795353) from @mih in the PR with some action items:

> From my POV this calls for an immediate move of GitRepo.get_indexed_files() into datalad/tests/utils.py only leaving a deprecated shim in GitRepo -- but no TODO for this PR.
Moreover, it seems that there is only a single user for file_has_content()left (in metadata.py) -- an important milestone for https://github.com/datalad/datalad/issues/4595.
Likewise time is running out for is_under_annex() only download_url(), add_archive_content() and that same metadata.py line are left TODO.

**Comment by bpoldrack** [comment]
Re general aspects of `normalize_paths`:

Just to be clear about it: The main idea was that a `*Repo` object should interprete relative paths given to its methods as relative to the repositories root rather than some PWD. Despite a similar logic being implemented higher level by now, I still think this is reasonable to have in an OOP conceptual sense. However, implementation is bad in performance and should not result in redoing anything, so I agree that the decorator needs to go - at the very least in its current form (for example, whether decorator or not, absolute paths should probably be a noop).

What turns out to be nonsense is the decorator's checking for paths being even part of the repository. This aspect should go, as we needed to have such checks higher-level anyway making it a waste or can simply let it fail down the road. No need to impose that cost at this level.

> A list of file names passed to a method will cause the all results to be assembled into a list before the method can communicate any results back to a caller (see match_return_type which is default-on)

Absolutely true (since there were no generators, when it was written), but can be changed by changing the implementation of this (or a intention-wise similar decorator/helper).

Ultimately, I think the originally intended functionality of it, is still desirable. However, the implementation of the idea needs to perform much better and account for the fact, that we are switching more and more to generators. The latter aspect, however, does indeed change behavior of the decorated methods, so we'd want to be able to replace or change them one by one.


Re migration:

I don't think there's a need for deprecation cycles of all those `*Repo` methods at the same time (possibly not even all of them period). The user-facing behavior of those decorated methods (how to interprete given paths and what kind of thing to return) isn't the pressing issue, but the decorator and how it's implemented is. Callers to the decorated methods do not specify the decorator's arguments. Only a method that we'd like turn into a generator would need replacement or behavior change. What needs deprecation from my point of view is the decorator(s) to stop the potential spread of use in (third-party) code. Now, simply doing that, would trigger lots of deprecation warnings from within our own code base, if it wasn't a complete replacement in one go. Hence, I would suggest the following:

1. Stop the spread and deprecate the decorator(s) as in: They actually issue deprecation warnings. In order to not spam callers with deprecation warnings they have no influence on and at the same time not requiring us to go to all decorated methods at once and decide how to proceed with them, we replace internal use by a `_migration_decorator`. Worst case it's just a plain copy of the old one, but we'd get the deprecation out of the way and clearly communicate `_internal_do_not_use`. Ideally, this replacement can already be more efficient (several things don't need to be done on a per-file basis).

2. This allows us to then attend to those methods separately. As I said before, I suspect there's at least part of the logic that we'd still want across them. Whether that ends up in a helper function or remains a decorator is to be determined. I guess, ideally we go through those methods and suck the decorator's functionality into them to the extend and in the form we deem right for this particular method (generator? possibly both current + a `generator_version_method_` as with the `call_git|annex` methods). In this step those methods should change to be not decorated but have them call the desired part of it as an `_internal` helper function. That does not necessarily imply a change of behavior of those methods for the caller! Hence, there's possibly no deprecation but simply a more efficient `method` and a generator alternative `method_`.

3. Going through 2 should give a bunch of little helpers. Finalizing, we can reextract a better decorator/helper (or several) that matches up-to-date needs and somewhat centralizes the path handling again to the extend it makes still sense in today's code base.

**Comment by mih** [comment]
I am closing this old issue of mine. There is clearly no interest in this.

**Comment by mih** [comment]
Also this is no longer an active issue, I want to put on record another undesired complexity that this decorator causes: platform path variability.

For example, I can pass a single POSIX path to `AnnexRepo.whereis()` just fine, on both linux and windows. In both cases I get the `whereis` info. However, only on windows the decorator does not unpack the info for a particular file, because `normalize_path` is unaware of the discrepancy between input and output for that method.
