### ISSUE TITLE
HCP (Human Connectome Project) support

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#579]
Original implementation will just expose data as available from S3

Due to a vast size in terms of # of files etc, further modularization is needed, so submodules will be provided per each subject, and within subject for different pre-processing schemes etc

Related
- [ ] https://github.com/datalad/datalad/issues/2  XNAT support since data originally distributed from XNAT, and then mirrored into S3. WiP: #1552 
- [ ] https://github.com/datalad/datalad/issues/5 Aspera support
- [ ] https://github.com/datalad/datalad/issues/32 slow operations on indirect repos (might be better or worse with v6 style repos, yet to check)
- [ ] #1671 commands for checkout/merge on hierarchy of the datasets

**Comment by mih** [comment]
This issue was moved to datalad/datasets#10

**Comment by mih** [comment]
Not sure why I reopened it.
