### ISSUE TITLE
datalad.interface.utils RF

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6005]
- [ ] `datalad/interface/utils.py:get_tree_roots` is only used by `save()` and untested
- [ ] `datalad/interface/utils.py:handle_dirty_dataset` is only used by `drop` and `remove`, also see #4594
- [x] `datalad/interface/utils.py:cls2cmdlinename` is unused, semi-redundant with `datalad/interface/utils.py:get_cmdline_command_name` [EDIT: ceased to exist #6392]
- [x] `datalad/interface/utils.py:path_is_under` only used by `remove` [EDIT: ceased to exist in #6392]
- [ ] `datalad/interface/utils.py:discover_dataset_trace_to_targets` only used by `save` and the to-be-replaced `aggregate_metadata()`

**Comment by mih** [comment]
`drop` and `remove` have now been reimplemented and use none of this functionality anymore.

**Comment by mih** [comment]
I am closing this old issue of mine. There is clearly no interest in this.
