### ISSUE TITLE
python 3.10 support/failing tests

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6362]
while building a debian package from current master snapshot

```
======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_get
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.15.4+git528.g4ea21cb32/.pybuild/cpython3_3.10_datalad/build/datalad/tests/utils.py", line 851, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.15.4+git528.g4ea21cb32/.pybuild/cpython3_3.10_datalad/build/datalad/tests/utils.py", line 851, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.15.4+git528.g4ea21cb32/.pybuild/cpython3_3.10_datalad/build/datalad/support/tests/test_annexrepo.py", line 933, in test_AnnexRepo_get
    with patch.object(GitWitlessRunner, 'run_on_filelist_chunks',
  File "/usr/lib/python3.10/unittest/mock.py", line 1635, in _patch_object
    return _patch(
  File "/usr/lib/python3.10/unittest/mock.py", line 1285, in __init__
    _check_spec_arg_typos(kwargs)
  File "/usr/lib/python3.10/unittest/mock.py", line 1261, in _check_spec_arg_typos
    raise RuntimeError(
RuntimeError: 'auto_spec' might be a typo; use unsafe=True if this is intended

======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_annex_version_handling_at_min_version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.15.4+git528.g4ea21cb32/.pybuild/cpython3_3.10_datalad/build/datalad/tests/utils.py", line 851, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.15.4+git528.g4ea21cb32/.pybuild/cpython3_3.10_datalad/build/datalad/support/tests/test_annexrepo.py", line 1599, in test_annex_version_handling_at_min_version
    po = patch.object(AnnexRepo, '_check_git_annex_version',
  File "/usr/lib/python3.10/unittest/mock.py", line 1635, in _patch_object
    return _patch(
  File "/usr/lib/python3.10/unittest/mock.py", line 1285, in __init__
    _check_spec_arg_typos(kwargs) 
  File "/usr/lib/python3.10/unittest/mock.py", line 1261, in _check_spec_arg_typos 
    raise RuntimeError( 
RuntimeError: 'auto_spec' might be a typo; use unsafe=True if this is intended

======================================================================
FAIL: datalad.cmdline.tests.test_main.test_help_np
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.15.4+git528.g4ea21cb32/.pybuild/cpython3_3.10_datalad/build/datalad/cmdline/tests/test_main.py", line 134, in test_help_np
    assert_in(s, sections)
AssertionError: 'Global options' not found in ['Essential commands', 'Commands for collaborative workflows', 'Dataset operations', 'Commands for metadata handling', 'Miscellaneous commands', 'Plumbing commands', 'General information']
```

my plan
- [x] look into fixing these fails (in `maint` where applicable, didn't check) (#6363)
- [x] in `maint`: update travis to add 3.10 run (#6363)
- [x] in `master`: make 3.7 as the minimal supported version (in CI and setup.py) (#6364)

**Comment by adswa** [comment]
Do I see correctly that  #6362 has fixed this issue? Please reopen if I am mistaken
