### ISSUE TITLE
0.17.0 Changelog

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6786]
Today `git log --format="? %s%n %h" --reverse --first-parent 0.16.6..HEAD | grep '?' | grep 'pull' | sed -e 's,^\?.*#,- [ ] #,'` yield the following PRs to consider for the 0.17 changelog

- [x] #6648 from yarikoptic/rf-no-asyncio2
- [x] #6663 from adswa/bf-6630
- [x] #6273 from jwodder/gh-6225
- [x] #6667 from mih/bf-5153
- [x] #6683 from bpoldrack/deprecated-addurl
- [x] #6675 from bpoldrack/sr-logging
- [x] #6684 from jdkent/doc/fast_addurls
- [x] #6670 from mih/rf-dstests
- [x] #6687 from datalad/contributors/update-2022-05-09
- [x] #6671 from mih/rf-siblingstest
- [x] #6674 from mih/rf-testget
- [x] #6672 from mih/rf-testupdate
- [x] #6689 from datalad/contributors/update-2022-05-09
- [x] #6664 from adswa/wtf-fs
- [x] #6698 from adswa/doc-doi
- [x] #6709 from jwodder/rewrite-utils-pytest
- [x] #6701 from adswa/enh-gitlab
- [x] #6716 from adswa/doc-lang
- [x] #6704 from adswa/enh-unlock-pbs
- [x] #6722 from adswa/mnt-6432
- [x] #6735 from mih/updateprogress
- [x] #6747 from mih/mnt-progresslog
- [x] #6739 from adswa/enh-progress-addarchivecontent
- [x] #6738 from adswa/mnt-6652
- [x] #6734 from mih/progressdocs
- [x] #6745 from adswa/mnt-export-archive
- [x] #6690 from bpoldrack/rm-testrepos
- [x] #6706 from adswa/mnt-6644
- [x] #6746 from mih/doclog
- [x] #6757 from jwodder/data-pkgs
- [x] #6756 from yarikoptic/enh-log-progress-start
- [x] #6783 from mih/rf-remove
- [x] #6792 from datalad/contributors/update-2022-07-02
- [x] #6794 from datalad/contributors/update-2022-07-02
- [x] #6790 from mih/bf-6547
- [x] #6802 from adswa/docs-docstrings
- [x] #6795 from mih/bf-4967-again
- [x] #6807 from yarikoptic/bf-CPs-from-master
- [x] #6799 from christian-monch/fix-ssh-copy-test
- [x] #6518 from christian-monch/enh-ng-metadata-search

**Comment by mih** [comment]
# 0.17.0 (... Jul .. 2022) -- 

#### 💫 Enhancements and new features
- "log" progress bar now reports about starting a specific action as well. [#6756](https://github.com/datalad/datalad/pull/6756) (by @yarikoptic)
- Documentation and behavior of traceback reporting for log messages via `DATALAD_LOG_TRACEBACK` was improved to yield a more compact report. The documentation for this feature has been clarified. [#6746](https://github.com/datalad/datalad/pull/6746) (by @mih)
- `datalad unlock` gained a progress bar. [#6704](https://github.com/datalad/datalad/pull/6704) (by @adswa)
- When `create-sibling-gitlab` is called on non-existing subdatasets or paths it now returns an impossible result instead of no feedback at all. [#6701](https://github.com/datalad/datalad/pull/6701) (by @adswa)
- `datalad wtf` includes a report on file system types of commonly used paths. [#6664](https://github.com/datalad/datalad/pull/6664) (by @adswa)

#### 🪓 Deprecations and removals
- Remove unused and untested log helpers `NoProgressLog` and `OnlyProgressLog`. [#6747](https://github.com/datalad/datalad/pull/6747) (by @mih)
- Remove unused `sorted_files()` helper. [#6722](https://github.com/datalad/datalad/pull/6722) (by @adswa)
- Discontinued the value `stdout` for use with the config variable `datalad.log.target` as its use would inevitably break special remote implementations. [#6675](https://github.com/datalad/datalad/pull/6675) (by @bpoldrack)
- `AnnexRepo.add_urls()` is deprecated in favor of `AnnexRepo.add_url_to_file()` or a direct call to `AnnexRepo.call_annex()`. [#6667](https://github.com/datalad/datalad/pull/6667) (by @mih)
- `datalad test` command and supporting functionality (e.g., `datalad.test`) were removed. [#](https://github.com/datalad/datalad/pull/6273) (by @jwodder)
#### 🐛 Bug Fixes
- `export-archive` does not rely on `normalize_path()` methods anymore and became more robust when called from subdirectories. [#6745](https://github.com/datalad/datalad/pull/6745) (by @adswa)
- Sanitize keys before checking content availability to ensure that the content availability of files with URL- or custom backend keys is correctly determined and marked. [#6663](https://github.com/datalad/datalad/pull/6663) (by @adswa)
- 
#### 📝 Documentation
- API documentation for log helpers, like `log_progress()` is now included in the renderer documentation. [#6746](https://github.com/datalad/datalad/pull/6746) (by @mih)
- New design document on progress reporting. [#6734](https://github.com/datalad/datalad/pull/6734) (by @mih)
- Explain downstream consequences of using `--fast` option in `addurls`. [#6684](https://github.com/datalad/datalad/pull/6684) (by @jdkent)

#### 🏠 Internal
- Inline code of `create-sibling-ria` has been refactored to an internal helper to check for siblings with particular names across dataset hierarchies in `datalad-next`, and is reintroduced into core to modularize the code base further. [#6706](https://github.com/datalad/datalad/pull/6706) (by @adswa)
- `get_initialized_logger` now lets a given `logtarget` take precendence over `datalad.log.target`. [#6675](https://github.com/datalad/datalad/pull/6675) (by @bpoldrack)
- Many uses of deprecated call options were replaced with the recommended ones. [#6273](https://github.com/datalad/datalad/pull/6273) (by @jwodder)
- Get rid of `asyncio` import by defining few noops methods from `asyncio.protocols.SubprocessProtocol` directly in `WitlessProtocol`. [#6648](https://github.com/datalad/datalad/pull/6648) (by @yarikoptic)
#### 🛡 Tests
- Discontinue use of `with_testrepos` decorator other than for the deprecation cycle for `nose`. [#6690](https://github.com/datalad/datalad/pull/6690) (by @mih @bpoldrack) See [#6144](https://github.com/datalad/datalad/issues/6144) for full list of changes.
- Remove usage of deprecated `AnnexRepo.add_urls` in tests. [#6683](https://github.com/datalad/datalad/pull/6683) (by @bpoldrack)
- Minimalistic (adapters, no assert changes, etc) migration from `nose` to `pytest`.
  Support functionality possibly used by extensions and relying on `nose` helpers is left in place to avoid affecting their run time and defer migration of their test setups.. [#6273](https://github.com/datalad/datalad/pull/6273) (by @jwodder)

#### 🚧 Infra

#### Authors: XX

- Yaroslav Halchenko (@yarikoptic)
- Michael Hanke (@mih)
- Benjamin Poldrack (@bpoldrack)
- Adina Wagner (@adswa)
- John T. Wodder (@jwodder)
